### ISSUE TITLE
My wallet don't meet requiments to anti-sybil.

### ISSUE THREAD

**Issue by Damexiak** [zkparty/trusted-setup-frontend#141] opened 2023-01-15 10:12 UTC
I used this wallet.. 0x7fB87Ff912b81A9211fb4cca2445643702bf5D33, and still my account don't meet anti-sibil account

**Comment by NicoSerranoP** [comment] 2023-01-16 01:51
Hi there! Sorry for this inconvenience, could you help me out answering these questions:

1. are you using it with Metamask?

2. could you check the development inspector console (Ctrl + Shift + I) and send me a screenshot of any errors (red colored)?

**Comment by Damexiak** [comment] 2023-01-18 16:59
Yes, am using with metamask..

**Comment by NicoSerranoP** [comment] 2023-01-19 02:49
This is a bit weird, what browser are you using?

Could you check if you can contribute using this other web client [dogekzg.com](https://www.dogekzg.com/) ? If the problem is with the sequencer it would prevent you from entering the lobby. If it allows you to go to the lobby then it might be a bug in this frontend :S

**Comment by Damexiak** [comment] 2023-01-19 12:25
i can&#39;t create the account.. because there is a deadline 
            
          
     
      
       
        Dnia 19 stycznia 2023 03:49 Nico Serrano ***@***.***&gt; napisał(a):
       
    
       
         
 This is a bit weird, what browser are you using? 
 Could you check if you can contribute using this other web client  www.dogekzg.com dogekzg.com  ? If the problem is with the sequencer it would prevent you from entering the lobby. If it allows you to go to the lobby then it might be a bug in this frontend :S

**Comment by Damexiak** [comment] 2023-01-19 12:26
user created after deadline... 
            
          
     
      
       
        Dnia 19 stycznia 2023 03:49 Nico Serrano ***@***.***&gt; napisał(a):
       
    
       
         
 This is a bit weird, what browser are you using? 
 Could you check if you can contribute using this other web client  www.dogekzg.com dogekzg.com  ? If the problem is with the sequencer it would prevent you from entering the lobby. If it allows you to go to the lobby then it might be a bug in this frontend :S

**Comment by NicoSerranoP** [comment] 2023-01-30 17:58
@Damexiak were you able to contribute? :) Can I close this issue?

**Closed by NicoSerranoP** 2023-01-30 17:58 UTC
